// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mathmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import org.mariuszgromada.math.mxparser.mathcollection.NumberTheory;

public class ConvertIntToBaseString extends CustomJavaAction<java.lang.String>
{
	private java.lang.Long Input;
	private java.lang.Long Base;
	private java.lang.Boolean IncludeBase;

	public ConvertIntToBaseString(IContext context, java.lang.Long Input, java.lang.Long Base, java.lang.Boolean IncludeBase)
	{
		super(context);
		this.Input = Input;
		this.Base = Base;
		this.IncludeBase = IncludeBase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		int baseInclude = (this.IncludeBase == null ? false : this.IncludeBase) ? 1 : 0;
		return NumberTheory.convDecimal2OthBase(this.Input, this.Base.intValue(), baseInclude);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConvertIntToBaseString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
