// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mathmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mathmodule.proxies.DecimalMoveDirection;

public class DecimalMovePoint extends CustomJavaAction<java.math.BigDecimal>
{
	private java.math.BigDecimal Input;
	private java.lang.Long MoveAmount;
	private mathmodule.proxies.DecimalMoveDirection Direction;

	public DecimalMovePoint(IContext context, java.math.BigDecimal Input, java.lang.Long MoveAmount, java.lang.String Direction)
	{
		super(context);
		this.Input = Input;
		this.MoveAmount = MoveAmount;
		this.Direction = Direction == null ? null : mathmodule.proxies.DecimalMoveDirection.valueOf(Direction);
	}

	@java.lang.Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.Input == null) {
			return null;
		}
		if (this.MoveAmount == null) {
			return this.Input;
		}
		int amount = this.MoveAmount.intValue();
		if (this.Direction.equals(DecimalMoveDirection.left)) {
			return this.Input.movePointLeft(amount);
		}
		return this.Input.movePointRight(amount);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DecimalMovePoint";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
