// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mathmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import org.mariuszgromada.math.mxparser.mXparser;
import mathmodule.proxies.Help;
import mathmodule.proxies.ShowHelpTextEnum;

public class ShowHelpText extends CustomJavaAction<IMendixObject>
{
	private mathmodule.proxies.ShowHelpTextEnum Parameter;

	public ShowHelpText(IContext context, java.lang.String Parameter)
	{
		super(context);
		this.Parameter = Parameter == null ? null : mathmodule.proxies.ShowHelpTextEnum.valueOf(Parameter);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMendixObject result = Core.instantiate(getContext(), Help.getType());
		
		if (this.Parameter.equals(ShowHelpTextEnum.constants)) {
			result.setValue(getContext(), Help.MemberNames.Text.toString(), mXparser.getHelp("constant"));
		} else if (this.Parameter.equals(ShowHelpTextEnum.units)) {
			result.setValue(getContext(), Help.MemberNames.Text.toString(), mXparser.getHelp("Unit"));
		} else if (this.Parameter.equals(ShowHelpTextEnum.full)) {
			result.setValue(getContext(), Help.MemberNames.Text.toString(), mXparser.getHelp());
		}
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ShowHelpText";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
