// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mathmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mathmodule.Misc;
import mathmodule.proxies.ExpressionUseEnum;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import org.mariuszgromada.math.mxparser.Expression;
import java.math.BigDecimal;
import org.mariuszgromada.math.mxparser.Argument;

public class ComplexExpression extends CustomJavaAction<IMendixObject>
{
	private java.lang.String Expression;
	private java.util.List<IMendixObject> __Arguments;
	private java.util.List<mathmodule.proxies.Argument> Arguments;

	public ComplexExpression(IContext context, java.lang.String Expression, java.util.List<IMendixObject> Arguments)
	{
		super(context);
		this.Expression = Expression;
		this.__Arguments = Arguments;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Arguments = new java.util.ArrayList<mathmodule.proxies.Argument>();
		if (__Arguments != null)
			for (IMendixObject __ArgumentsElement : __Arguments)
				this.Arguments.add(mathmodule.proxies.Argument.initialize(getContext(), __ArgumentsElement));

		// BEGIN USER CODE
		IContext ctx = this.getContext();
		
		if (this.Expression == "" || this.Expression == null) {
			return Misc.getExpressionError(ctx, "Expression cannot be empty");
		}
		
		Expression expression = new Expression(this.Expression);
		for(mathmodule.proxies.Argument argument : this.Arguments) {
			IMendixObject obj = argument.getMendixObject();
			
			String name = obj.getValue(ctx, mathmodule.proxies.Argument.MemberNames.ArgumentName.toString());
			BigDecimal value = obj.getValue(ctx, mathmodule.proxies.Argument.MemberNames.Value.toString());
			String stringValue = obj.getValue(ctx, mathmodule.proxies.Argument.MemberNames.StringValue.toString());
			String enumeration = obj.getValue(ctx, mathmodule.proxies.Argument.MemberNames.Use.toString());
			
			if (enumeration.equals(ExpressionUseEnum.Decimal.name()) && value != null) {
				Argument arg = new Argument(name, value.doubleValue());
				expression.addArguments(arg);
			} else if (enumeration.equals(ExpressionUseEnum.String.name()) && stringValue != null) {
				double doubleValue = new Double(stringValue);
				if (!Double.isNaN(doubleValue)) {
					Argument arg = new Argument(name, doubleValue);
					expression.addArguments(arg);
				}
			}
		}
		
		boolean syntaxValid = expression.checkSyntax();
		if (syntaxValid) {
				
			double expressionResult = expression.calculate();
			boolean afterCalculateSatus = expression.checkSyntax();
			
			if (afterCalculateSatus) {
				if (Double.isNaN(expressionResult)) {
					return Misc.getExpressionError(ctx, "Expression result is not a number");
				}
				return Misc.getExpressionResult(ctx, expressionResult);
			} else {
				return Misc.getExpressionError(ctx, expression.getErrorMessage());
			}

		} else {
			return Misc.getExpressionError(ctx, expression.getErrorMessage());
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ComplexExpression";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
